### ISSUE TITLE
In Latexmk-sentinel: auctex-latexmk.el:136:45:Error: missing value for ‘TeX-command-default’ at end of setq

### ISSUE THREAD

**Issue by smallzhan** [tom-tan/auctex-latexmk#19]
When installed from melpa, the error message shows as title.
line 136 of the auctex-latexmk.el is  

    (when (string= TeX-command-next TeX-command-BibTeX)
              (setq TeX-command-default))

seems that something is missing.  after the (setq ....)

emacs version 25.1.50.1

**Comment by tom-tan** [comment]
It is because it used an undocumented behavior of `setq`.
I fixed it.

Please check the latest version.

**Comment by tom-tan** [comment]
I close this issue.
Please reopen if it is not fixed yet.
