### ISSUE TITLE
Support for XeTeX and LuaTeX

### ISSUE THREAD

**Issue by pkkm** [tom-tan/auctex-latexmk#20]
I think it would be nice if `latexmk` was called with the `-xelatex` parameter when `TeX-engine` is set to `xetex`, and with the `-lualatex`parameter when `TeX-engine` is `luatex`. This would make `auctex-latexmk` work out-of-the-box with XeLaTeX and LuaLaTeX documents.

**Comment by tom-tan** [comment]
Sorry for late reply.

I added `-xelatex` and `-lualatex` support to the latest version.
Please check it.

**Comment by pkkm** [comment]
Thanks! After deleting an extraneous pair of parentheses and changing string to symbol comparison, I can confirm that the package now supports XeLaTeX and LuaLaTeX documents. I sent these small changes in pull request #21.
