### ISSUE TITLE
Support MELPA stable

### ISSUE THREAD

**Issue by gdv** [tom-tan/auctex-latexmk#25]
Thanks for your great package!

[Melpa stable](https://stable.melpa.org/) accepts only stable versions of packages (while MELPA takes the latest commit of each package). So *auctex-latexmk* is not available via Melpa stable.
To make it happen, you should tag the latest commit vith a [semver](http://www.semver.org) version.
For example, giving the following commands should suffice:
```
git tag v1.0.0 bda696babcf4f4df435415e2d6a9c54fa99b230c
git push
```

Since tagging cannot be done via a pull request, I cannot help you more.
Thanks!

**Comment by tom-tan** [comment]
Done!

**Comment by gdv** [comment]
Great, thanks
