### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by alvarouc** [tom-tan/auctex-latexmk#29]
I got this error running in emacs 22.1

package-install-from-archive: http://melpa.org/packages/auctex-latexmk-20160923.7.el: Not found

**Comment by tom-tan** [comment]
It is an older version of auctex-latexmk.
Please use the link for latest one (http://melpa.org/packages/auctex-latexmk-20170618.936.el) or
use `package.el` (bundled with newer version of Emacs) that can manage packages in Melpa and other repositories.

**Comment by alvarouc** [comment]
Thanks, that fixed it
