### ISSUE TITLE
Cannot view pdf when option $out_dir is set in latexmkrc

### ISSUE THREAD

**Issue by j-jith** [tom-tan/auctex-latexmk#31]
My latexmrc is just a single line:
```
$out_dir = 'build';
```

After I run the LatexMk command, if I try to view the output (C-c C-v), I get an error saying that the output file cannot be found. Would it be possible to parse the latexmkrc (in the current directory as well as in the home directory) to see if `$out_dir` is set, and then modify the view command?

Temporarily, I have fixed this by adding another line to my latexmkrc:
```
$pdflatex .= '&& (cp "%D" "%R.pdf"; cp "%Z%R.synctex.gz" "%R.synctex.gz")'
```
This line copies the output pdf and synctex files to the current directory. I'm able to C-c C-v successfully after this.

**Comment by rbbernardino** [comment]
I had the same issue and adopted another solution: **change the "View" command**!
You may see that when you issue a `C-c C-v`, the command to call your viewer appears. We need to add a `build/` before the file name.

Each program has a slightly different calling method, so to find out what is it, for example, for Evince:
`M-x [RET] describe-variable [RET] TeX-view-program-list-builtin [RET]`
Search for your program, ex. Evince:
`C-s evince`
You'll see the lines:
```lisp
("Evince"
        ("evince"
        (mode-io-correlate " -p %(outpage)")
        " %o")
    "evince")
```

Just change `" %o"` to `" build/%o"`, notice the space before build!

To apply such a change, in my `.emacs`, I have: (I use Okular)
```emacs
(defun okular-view-LaTeX-mode()
  (add-to-list 'TeX-view-program-list
			   '("Okular" ("okular --unique build/%o" (mode-io-correlate "#src:%n%a"))))
  (setq TeX-view-program-selection '((output-pdf "Okular"))))
(add-hook 'LaTeX-mode-hook 'okular-view-LaTeX-mode)
```

You may change to your program and it's calling method.

**Comment by tom-tan** [comment]
Sorry for late reply.

IMO the way @rbbernardino suggested is a reasonable solution for it.
Otherwise it will need too much work to support `$out_dir` in `auctex-latexmk` (I guess it is almost equivalent to implement a subset of Perl interpreter :-( ).

**Comment by j-jith** [comment]
I agree that what @rbbernardino has suggested is a satisfactory solution for this problem. I'll close this issue then, if you don't mind.

If you are interested, we had a similar issue in the vim plugin vimtex (lervag/vimtex#701). It was fixed with a function that parses latexmkrc with some regexp trickery.

**Comment by tom-tan** [comment]
Thank you for the information!
I will take a look.
