### ISSUE TITLE
How to add shell-escape option

### ISSUE THREAD

**Issue by thorstengrothe** [tom-tan/auctex-latexmk#32]
Hi,

In my latexmkrc file I added this line for shell escape 

```
$pdf_mode = 1;
$pdflatex = '--shell-escape';
```
but autctex-latexmk seems to overwrite my settings, this is the output from auctex

`Running `LatexMk' on `DE_Rechtschreibung' with ``latexmk -pdf -pdflatex=xelatex --synctex=1 -interaction=nonstopmode  -file-line-error  DE_Rechtschreibung.tex''
`

How can I set shell escape correctly?

Regards
Thorsten

**Comment by robertodr** [comment]
I'm affected too.

**Comment by tom-tan** [comment]
Sorry for late reply.

It is a misconfiguration of `.latexmkrc`.
`$pdflatex` is to set the command and options for `pdflatex` rather than only options for `pdflatex`.
Here is a working example:
```perl:
$pdf_mode = 1;
$pdflatex = 'pdflatex --shell-escape';
```

**Comment by thorstengrothe** [comment]
Sorry I did not see your  answer. 
In newer auctex versions (12.1.1) this seems to be default, so I do not have to change anything :-)
Another way in emacs would be:
``` 
  (setq
   ;; Compilation settings
   TeX-engine-alist
   '((xetex "XeTeX -shell escape"
            "xetex -shell-escape"
            "xelatex -shell-escape"))
```

**Comment by tom-tan** [comment]
OK, I close this issue.
If there is another problem, please open a new issue.
