### ISSUE TITLE
tex-buf.el has been merged into tex.el

### ISSUE THREAD

**Issue by tarsius** [tom-tan/auctex-latexmk#44]
I've noticed this because I maintain the [Emacsmirror](https://emacsmirror.org) and the tools, that I use to do so, inform me when a dependency of a mirrored package isn't satisfied (anymore).

In `auctex` [`tex-buf.el` was merged into `tex.el`](https://github.com/emacsmirror/auctex/commit/4b1c7015ae77b88832af35510232e1a1b716da3a) but your package still `require`s `tex-buf`. You can probably fix this by depending on `tex` instead, or if you already do that by dropping the additional `(require 'tex-buf)`.

**Comment by kngwyu** [comment]
I feel like it's better if @emacsorphanage or some orgs take over the maintenance after contacting the maintainer.

**Comment by ThibautVerron** [comment]
An easy work-around for users waiting for an update is to add `(provide 'tex-buf)` in the init file before loading `auctex-latexmk`.

**Comment by tarsius** [comment]
Fixed in pending #40.

**Comment by tarsius** [comment]
I have added a patch to the version on the Emacsmirror to fix this issue, and have updated Melpa to get this package from there.

**Comment by tarsius** [comment]
Closing to get this of the list of my issues to occasionally revisit. #40 is still open, so that serves as a visible pointer to the current workaround (using the version from the Emacsmirror).
